spring.application.name=backend

# Configuración del servidor
server.port=8080

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BD_MOBI
spring.datasource.username=postgres
spring.datasource.password=esteban
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de JWT
jwt.secret=6f801f12fe402509849420bb31eded29b6873a50ca031bb433c558fdc164618b
jwt.expiration=86400000 # 1 día en milisegundos

# Configuración de Spring Security (Cors y CSRF)
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*